# Writes web-demo\config.txt from each chain's multichain.conf + params.dat, checks PHP has curl,
# then serves the MultiChain Web Demo with PHP's built-in web server.
# -Chain takes one chain or several separated by spaces/commas, e.g. -Chain "PaymentChain ServiceChain".
param([string]$Chain, [switch]$ConfigOnly)
$ChainList = @($Chain -split '[\s,]+' | Where-Object { $_ })
if ($ChainList.Count) { $Chain = $ChainList[0] }
. (Join-Path $PSScriptRoot 'common.ps1')
if (-not $ChainList.Count) { $ChainList = @($Chain) }

$webDemo = (Resolve-Path (Join-Path $PSScriptRoot '..\..\web-demo')).Path

# 1. config.txt - one section per chain ("default" when there is only one, as in the web demo's example)
$lines = @('# Generated by scripts/windows/web-demo.ps1 - contains the RPC passwords, do not share.')
$rpcPorts = @{}
foreach ($c in $ChainList) {
    $Chain = $c
    $ChainDir = Join-Path $DataDir $c
    Assert-ChainCreated
    $conf = Read-Conf (Join-Path $ChainDir 'multichain.conf')
    $params = Read-ParamsDat (Join-Path $ChainDir 'params.dat')
    $rpcPorts[$c] = $params['default-rpc-port']
    if ($ChainList.Count -gt 1) { $prefix = $c; $label = $c } else { $prefix = 'default'; $label = "$c (local node)" }
    $lines += @("$prefix.name=$label", "$prefix.rpchost=127.0.0.1", "$prefix.rpcsecure=0",
                "$prefix.rpcport=$($rpcPorts[$c])", "$prefix.rpcuser=$($conf['rpcuser'])",
                "$prefix.rpcpassword=$($conf['rpcpassword'])", '')
}
$config = $lines -join "`r`n"
$configPath = Join-Path $webDemo 'config.txt'
[System.IO.File]::WriteAllText($configPath, $config, (New-Object System.Text.UTF8Encoding($false)))
Write-Title "Wrote $configPath"
Write-Host ($config -replace 'rpcpassword=.*', 'rpcpassword=********')
if ($ConfigOnly) { return }

# 2. PHP + curl extension
if (-not (Test-Path -LiteralPath $PhpExe)) { Stop-WithMessage "php.exe not found at $PhpExe - fix PHP_EXE in settings.txt" }
$phpArgs = @()
if (-not ((& $PhpExe -m) -contains 'curl')) {
    $extDir = Join-Path (Split-Path -Parent $PhpExe) 'ext'
    $phpArgs = @('-d', "extension_dir=$extDir", '-d', 'extension=curl')
    if (-not ((& $PhpExe @phpArgs -m) -contains 'curl')) {
        Stop-WithMessage "PHP curl extension is not available. In php.ini set extension_dir=""$extDir"" and uncomment extension=curl"
    }
    Write-Host "curl is not enabled in php.ini - enabling it for this run with: $($phpArgs -join ' ')" -ForegroundColor DarkYellow
}
& $PhpExe -v | Select-Object -First 1 | Write-Host

# 3. node check (the demo still loads without it, but that chain's pages will show a connection error)
foreach ($c in $ChainList) {
    $Chain = $c
    if (Test-NodeRunning) {
        Write-Host "Node '$c' is running - RPC port $($rpcPorts[$c])" -ForegroundColor Green
    } else {
        Write-Host "WARNING: node '$c' is not running - start it with 02-start-node.bat $c" -ForegroundColor Red
    }
}

# 4. serve (E_ALL minus deprecation notices = 24575)
$url = "http://127.0.0.1:$WebPort/"
Write-Title "Web demo: $url   (press Ctrl+C to stop)"
try { Start-Process $url } catch { Write-Host "Open $url in your browser." }
& $PhpExe @phpArgs -d display_errors=1 -d error_reporting=24575 -S "127.0.0.1:$WebPort" -t $webDemo
