# Writes web-demo\config.txt from the chain's multichain.conf + params.dat, checks PHP has curl,
# then serves the MultiChain Web Demo with PHP's built-in web server.
param([string]$Chain, [switch]$ConfigOnly)
. (Join-Path $PSScriptRoot 'common.ps1')

$webDemo = (Resolve-Path (Join-Path $PSScriptRoot '..\..\web-demo')).Path
Assert-ChainCreated

# 1. config.txt
$conf = Read-Conf (Join-Path $ChainDir 'multichain.conf')
$params = Read-ParamsDat (Join-Path $ChainDir 'params.dat')
$config = @(
    '# Generated by scripts/windows/web-demo.ps1 - contains the RPC password, do not share.',
    "default.name=$Chain (local node)",
    'default.rpchost=127.0.0.1',
    'default.rpcsecure=0',
    "default.rpcport=$($params['default-rpc-port'])",
    "default.rpcuser=$($conf['rpcuser'])",
    "default.rpcpassword=$($conf['rpcpassword'])",
    ''
) -join "`r`n"
$configPath = Join-Path $webDemo 'config.txt'
[System.IO.File]::WriteAllText($configPath, $config, (New-Object System.Text.UTF8Encoding($false)))
Write-Title "Wrote $configPath"
Write-Host ($config -replace 'rpcpassword=.*', 'rpcpassword=********')
if ($ConfigOnly) { return }

# 2. PHP + curl extension
if (-not (Test-Path -LiteralPath $PhpExe)) { Stop-WithMessage "php.exe not found at $PhpExe - fix PHP_EXE in settings.txt" }
$phpArgs = @()
if (-not ((& $PhpExe -m) -contains 'curl')) {
    $extDir = Join-Path (Split-Path -Parent $PhpExe) 'ext'
    $phpArgs = @('-d', "extension_dir=$extDir", '-d', 'extension=curl')
    if (-not ((& $PhpExe @phpArgs -m) -contains 'curl')) {
        Stop-WithMessage "PHP curl extension is not available. In php.ini set extension_dir=""$extDir"" and uncomment extension=curl"
    }
    Write-Host "curl is not enabled in php.ini - enabling it for this run with: $($phpArgs -join ' ')" -ForegroundColor DarkYellow
}
& $PhpExe -v | Select-Object -First 1 | Write-Host

# 3. node check (the demo still loads without it, but every page will show a connection error)
if (Test-NodeRunning) {
    Write-Host "Node '$Chain' is running - RPC port $($params['default-rpc-port'])" -ForegroundColor Green
} else {
    Write-Host "WARNING: node '$Chain' is not running - start it with 02-start-node.bat" -ForegroundColor Red
}

# 4. serve (E_ALL minus deprecation notices = 24575)
$url = "http://127.0.0.1:$WebPort/"
Write-Title "Web demo: $url   (press Ctrl+C to stop)"
try { Start-Process $url } catch { Write-Host "Open $url in your browser." }
& $PhpExe @phpArgs -d display_errors=1 -d error_reporting=24575 -S "127.0.0.1:$WebPort" -t $webDemo
